### ISSUE TITLE
Recording failures after firmware update

### ISSUE THREAD

**Issue by pivotal-jack** [OpenAcousticDevices/AudioMoth-Firmware-Basic#11]
Hello, 

I have quite a few audio moths that were working well, and I upgraded a few to the newest firmware (1.10.1). I am now having an issue where recording fails intermittently (sometimes after a few minutes, sometimes after a few hours), particularly at higher sampling frequencies (>= 92 kHz). None of the devices on the new firmware have lasted the scheduled 48 hours (recording 55-secs ON/5-sec OFF). At first I thought it was an SD card issue, but it even happens with the supported SanDisk Extreme 128GB cards. 

I've rolled back those moths to older firmware versions, but the issue is persisting. Is there a way to "hard reset" to older firmware versions? I'm happy to provide more context or other info that you need; just let me know.

Thank you!

**Comment by AlexRogersCS** [comment]
Hi, Can you move this query to the forum - https://www.openacousticdevices.info/support. It sounds like the batteries are low so the AudioMoth stops recording. Can you use the 'Summarise AudioMoth Files' option in the Config App to summarise the contents of one of the SD cards. If you've rolled back the firmware, the issue is with the device, SD card or batteries, as nothing is persistent after a reflash of the firmware. Alex

**Comment by pivotal-jack** [comment]
Will do - thanks for the reply
