### ISSUE TITLE
sensor serial number prefix on file name

### ISSUE THREAD

**Issue by abfleishman** [OpenAcousticDevices/AudioMoth-Firmware-Basic#4]
Feature Request:
Most sensors on the market write a prefix to files that specify by which sensor the file was made.  This makes keeping track of files much easier as you do not have to have "correct" folder names to keep things organized or read the metadata.  

I would request that the file name start with the serial number of the unit, and then follow the current naming conventions.  serial_yyyymmddhhmmss.WAV

**Comment by Friessn** [comment]
In general, I would second this request since I always add the aforementioned prefix via bash script afterwards. However, I am not sure if everybody is aware of the great feature that every file has metadata - including the serial number - embedded that can conveniently be retrieved via exiftool. I think this really useful feature is not mentioned anywhere on openacousticdevices.info and I would recommend mentioning it more prominently. Especially as this data can be lost during flac compression. I think I found the information on the great guide of [Tessa Rhinehart](https://github.com/rhine3/audiomoth-guide)

**Comment by AlexRogersCS** [comment]
We'll look at adding this as a firmware option.

**Comment by abfleishman** [comment]
I see that this issue was closed.  I have not seen this option, did it get done or nixed?

**Comment by AlexRogersCS** [comment]
It'll get added in a future update. It will potentially break a lot of the tools (e.g. expansion, split, etc) so they'll also need updating to correctly recognise AudioMoth files.
